apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crossargo-sync
  name: crossargo-sync
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crossargo-sync
  strategy: {}
  template:
    metadata:
      labels:
        app: crossargo-sync
    spec:
      serviceAccount: crossargo-sync
      containers:
        - image: exocode/crossargo-sync
          name: crossargo-sync
          resources: {}
          env: # namespace where to search for kubeconfig secrets
            - name: CREDENTIAL_NAMESPACE
              value: "default"
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: user
  name: crossargo-sync
---
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: user
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: user
subjects:
  - kind: ServiceAccount
    name: crossargo-sync
    namespace: user
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-secrets
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: crossargo-sync
    namespace: user
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
---
#################################################################################
# add role and rolebinding to access the namespace where kubeconfigs are stored
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeconfig-reader
  namespace: crossplane-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-kubeconfigs
  namespace: crossplane-system
subjects:
  - kind: ServiceAccount
    name: crossargo-sync
    namespace: user
roleRef:
  kind: Role
  name: kubeconfig-reader
  apiGroup: rbac.authorization.k8s.io
